/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RevoUiAvatar {
        /**
          * The background color to use. If none and @randomColor = true, generate automatically.
         */
        "backgroundColor": string;
        /**
          * The background color opacity.
         */
        "backgroundColorOpacity": number;
        /**
          * Is circle
         */
        "circle": boolean;
        /**
          * The font color to use if no image is provided.
         */
        "color": string;
        /**
          * Force the displayed initials by overriding the computed ones.
         */
        "initials": string;
        /**
          * Uses inline-flex instead of flex
         */
        "inline": boolean;
        /**
          * Is main background is light
         */
        "isLight": boolean;
        /**
          * The title that will be used to compute user initial.
         */
        "name": string;
        /**
          * Generate random color
         */
        "randomColor": boolean;
        /**
          * Rectangle size
         */
        "size": number;
        /**
          * Path to the avatar image to display.
         */
        "src": string;
    }
}
declare global {
    interface HTMLRevoUiAvatarElement extends Components.RevoUiAvatar, HTMLStencilElement {
    }
    var HTMLRevoUiAvatarElement: {
        prototype: HTMLRevoUiAvatarElement;
        new (): HTMLRevoUiAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "revo-ui-avatar": HTMLRevoUiAvatarElement;
    }
}
declare namespace LocalJSX {
    interface RevoUiAvatar {
        /**
          * The background color to use. If none and @randomColor = true, generate automatically.
         */
        "backgroundColor"?: string;
        /**
          * The background color opacity.
         */
        "backgroundColorOpacity"?: number;
        /**
          * Is circle
         */
        "circle"?: boolean;
        /**
          * The font color to use if no image is provided.
         */
        "color"?: string;
        /**
          * Force the displayed initials by overriding the computed ones.
         */
        "initials"?: string;
        /**
          * Uses inline-flex instead of flex
         */
        "inline"?: boolean;
        /**
          * Is main background is light
         */
        "isLight"?: boolean;
        /**
          * The title that will be used to compute user initial.
         */
        "name"?: string;
        /**
          * Generate random color
         */
        "randomColor"?: boolean;
        /**
          * Rectangle size
         */
        "size"?: number;
        /**
          * Path to the avatar image to display.
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "revo-ui-avatar": RevoUiAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "revo-ui-avatar": LocalJSX.RevoUiAvatar & JSXBase.HTMLAttributes<HTMLRevoUiAvatarElement>;
        }
    }
}
